#!/usr/bin/env python3
"""Embed firmware/*.bin as zlib-compressed C arrays.

Usage: python3 tools/gen_fw_blobs.py firmware build/gen/fw_blobs.c

The loader (src/compat/rtw88_firmware.c) looks images up by file name, so
"rtw89/rtw8852b_fw-1.bin" is found as firmware/rtw8852b_fw-1.bin. With no
images present the table is empty and the build still links; the driver then
fails at probe with "firmware not in embedded blobs".
"""
import sys
import zlib
from pathlib import Path


def main():
    fw_dir, out_c = Path(sys.argv[1]), Path(sys.argv[2])
    bins = sorted(fw_dir.glob("*.bin")) if fw_dir.is_dir() else []

    lines = ["/* Generated by tools/gen_fw_blobs.py - do not edit */",
             '#include "fw_blobs.h"', ""]
    entries = []
    for path in bins:
        raw = path.read_bytes()
        comp = zlib.compress(raw, 9)
        sym = "fw_" + "".join(c if c.isalnum() else "_" for c in path.name)
        entries.append((path.name, sym, len(comp), len(raw)))
        lines.append(f"static const uint8_t {sym}[] = {{")
        for i in range(0, len(comp), 16):
            lines.append("    " + ", ".join(f"0x{b:02x}" for b in comp[i:i + 16]) + ",")
        lines += ["};", ""]

    lines.append("const struct rtw88_fw_blob rtw88_fw_blobs[] = {")
    for name, sym, csz, osz in entries:
        lines.append(f'    {{ "{name}", {sym}, {csz}, {osz} }},')
    lines += ["    { 0, 0, 0, 0 }", "};"]

    out_c.parent.mkdir(parents=True, exist_ok=True)
    out_c.write_text("\n".join(lines) + "\n")
    if entries:
        orig = sum(e[3] for e in entries) // 1024
        comp = sum(e[2] for e in entries) // 1024
        print(f"  GEN  {out_c}: {len(entries)} image(s), {orig} KB -> {comp} KB")
    else:
        print(f"  GEN  {out_c}: no firmware in {fw_dir}/ (run `make fetch-firmware`)")


if __name__ == "__main__":
    main()
